theme: minima

title: hxiaom
author: hxiaom
email: hxiaom0117 (at) 163.com
description: > # this means to ignore newlines until "header_pages:"
  Xiaoming HUANG's Website

header_pages:
  - about.md
  - category.md
  - biography.md

# social links
github_username: hxiaom
rss: rss

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

# Pagination
paginate: 5
paginate_path: posts/page:num/

# Comments
disqus:
  shortname: hxiaom
