theme: minima

title: hxiaom
author: hxiaom
email: hxiaom0117 (at) 163.com
description: > # this means to ignore newlines until "header_pages:"
  # Xiaoming HUANG's Website

header_pages:
#  - about.md
  - methodologies.md
  # - research.md
  # - life.md
  # - archives.md
  # - biography.md
  - search.md

# social links
github_username: hxiaom
# rss: rss

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-archives

# Pagination
paginate: 8
paginate_path: posts/page:num/

# Comments
disqus:
  shortname: hxiaom

# Search
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.md, category.md, index.html]
  
# Formula
mathjax: true

# Archive
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'