# Site settings
title: HXIAOM Blog                    # 你的博客网站标题
SEOTitle: hxiaom的博客 | hxiaom Blog		# SEO 标题
description: "Hey"	   	   # 随便说点，描述一下

# SNS settings      
github_username: hxiaom     # 你的github账号
jianshu_username: e71990ada2fd  # 你的简书ID。

# Build settings
# paginate: 10              # 一页你准备放几篇文章